version: "3.8"
networks: # container간 통신 방식
  traveleye-network:
    driver: bridge
services:
  database:
    image: "mellykim123/mysql2"
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: traveleye
      MYSQL_ROOT_HOST: "%"
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 1234
      ports:
        -"3307:3306"
      volumes:
        -./:/var/lib/mysql
      networks:
        -traveleye-network

  springboot:
    image: "mellykim123/spring"
    ports:
      - "80:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/traveleye?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: "always"
