#version: '1.0'
#networks:
#  traveleye-network:
#    driver: bridge
#services:
#  traveleye-service:
#    networks:
#      - traveleye-network
#    build: "./"
#    container_name: "traveleye-service"
#    working_dir: "/app"
#    environment:
#      TZ: ""
#      SERVER_NAME: ""
#      HTTP_PORT: "3000"
#      DB_HOST: "traveleye-postgres"
#      DB_PORT: "5432"
#      DB_USER: "postgres"
#      DB_PASS: ""
#      DB_NAME: ""
#      REDIS_HOST: "traveleye-redis"
#      REDIS_PORT: "6379"
#      PASSWORD_ITERATION: ""
#      JWT_KEY_TTL: ""
#      JWT_ISSUER: ""
#      ACCESS_TTL: ""
#      REFRESH_TTL: ""
#      ALIGO_KEY: ""
#      ALIGO_ID: ""
#      ALIGO_SENDER: ""
#      IS_PROD: ""
#    ports:
#      - "3000:3000"
#    volumes:
#      - ../data/images:/app/images
#    links:
#      - "traveleye-redis"
#      - "traveleye-mysql"
#  traveleye-redis:
#    networks:
#      - traveleye-network
#    image: "redis:3"
#    ports:
#      - "63790:6379"
#    container_name: "traveleye-redis"
#  traveleye-mysql:
#    networks:
#      - traveleye-network
#    image: "mysql:latest"  # Use the MySQL image
#    ports:
#      - "3306:3306"  # Change the port to MySQL's default port
#    container_name: "traveleye-mysql"
#    volumes:
#      - ../data/db:/var/lib/mysql  # Adjust the volume path for MySQL
#    environment:
#      MYSQL_ROOT_PASSWORD: ""  # Set the root password for MySQL
#      MYSQL_DATABASE: "traveleye_database"  # Set the default database

version: "3.8"
networks: # container간 통신 방식
  traveleye-network:
    driver: bridge
services:
  database:
    image: mysql:8.1.0
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: traveleye
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ""
      ports: -"3307:3306"
      volumes:
            -./:/var/lib/mysql
      networks: -traveleye-network
#docker exec -entrypoint bin/bash
#docker image commit
#docker run -v (host folder 를 mount 시키기)
#docker copy
  springboot:
    image: "mellykim123/docker-test3:latest"
    ports:
      - "80:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/traveleye?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: "always"
